### ISSUE TITLE
Use Backspace key in the input area of input size causes everything to disappear

### ISSUE THREAD

**Issue by vra** [ezyang/convolution-visualizer#2]
Hi @ezyang,
Thanks for your useful tools. I found that when using `Backspace` key in the input area of `input size` causes everything to disappear. Could you help to fix this issue? Thanks.

I am using Ubuntu 16.04 and Chrome 70

**Comment by ezyang** [comment]
Confirmed.

**Comment by lucasjinreal** [comment]
@ezyang  Does there any fix solution now? Can not input size bigger than 16
